export const DOG_BREEDS = [
  "Affenpinscher", "Afghan Hound", "Airedale Terrier", "Akita", "Alaskan Malamute",
  "American Bulldog", "American Cocker Spaniel", "American Staffordshire Terrier",
  "Australian Cattle Dog", "Australian Shepherd", "Basenji", "Basset Hound", "Beagle",
  "Bearded Collie", "Bedlington Terrier", "Belgian Malinois", "Bernese Mountain Dog",
  "Bichon Frise", "Bloodhound", "Border Collie", "Border Terrier", "Borzoi",
  "Boston Terrier", "Bouvier des Flandres", "Boxer", "Briard", "Brittany",
  "Bull Terrier", "Bulldog", "Bullmastiff", "Cairn Terrier", "Cane Corso",
  "Cavalier King Charles Spaniel", "Cavapoo", "Chesapeake Bay Retriever", "Chihuahua",
  "Chinese Crested", "Chow Chow", "Cockapoo", "Cocker Spaniel", "Collie",
  "Coton de Tulear", "Dachshund", "Dalmatian", "Doberman Pinscher", "Dogue de Bordeaux",
  "English Setter", "English Springer Spaniel", "Field Spaniel", "Finnish Lapphund",
  "Flat-Coated Retriever", "Fox Terrier", "French Bulldog", "German Shepherd",
  "German Shorthaired Pointer", "Giant Schnauzer", "Golden Retriever", "Goldendoodle",
  "Great Dane", "Great Pyrenees", "Greyhound", "Havanese", "Hungarian Vizsla",
  "Irish Setter", "Irish Wolfhound", "Italian Greyhound", "Jack Russell Terrier",
  "Japanese Chin", "Keeshond", "Labradoodle", "Labrador Retriever", "Lagotto Romagnolo",
  "Lhasa Apso", "Maltese", "Maltipoo", "Mastiff", "Miniature Pinscher",
  "Miniature Poodle", "Miniature Schnauzer", "Newfoundland", "Norfolk Terrier",
  "Norwich Terrier", "Old English Sheepdog", "Papillon", "Patterdale Terrier",
  "Pekingese", "Pembroke Welsh Corgi", "Pomeranian", "Poodle", "Portuguese Water Dog",
  "Pug", "Puggle", "Rhodesian Ridgeback", "Rottweiler", "Saint Bernard", "Saluki",
  "Samoyed", "Schipperke", "Schnauzer", "Schnoodle", "Scottish Terrier",
  "Shar Pei", "Sheltie", "Shiba Inu", "Shih Tzu", "Shih-poo", "Siberian Husky",
  "Sloughi", "Soft Coated Wheaten Terrier", "Spanish Water Dog", "Springerdoodle",
  "Staffordshire Bull Terrier", "Standard Poodle", "Standard Schnauzer",
  "Tibetan Terrier", "Toy Poodle", "Vizsla", "Weimaraner", "Welsh Springer Spaniel",
  "Welsh Terrier", "West Highland White Terrier", "Whippet", "Wire Fox Terrier",
  "Yorkipoo", "Yorkshire Terrier", "Crossbreed / Mixed", "Other",
] as const;

export const TREATMENTS = [
  "Full Groom",
  "Bath & Brush / Deshed",
  "Hand Stripping",
  "Puppy Groom",
  "Ultrasound Teeth Cleaning",
  "Walk-in Nail Trim",
  "Face & Hygiene Trim",
  "Ear Clean",
  "Pad Clip-out",
  "Not sure — please advise",
] as const;
