/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteBookRouteImport } from './routes/_site.book'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteServicesRouteImport } from './routes/_site.services'
import { Route as SiteVisitRouteImport } from './routes/_site.visit'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBookRoute = SiteBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SiteVisitRoute = SiteVisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/book': typeof SiteBookRoute
  '/contact': typeof SiteContactRoute
  '/services': typeof SiteServicesRoute
  '/visit': typeof SiteVisitRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/book': typeof SiteBookRoute
  '/contact': typeof SiteContactRoute
  '/services': typeof SiteServicesRoute
  '/visit': typeof SiteVisitRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/book': typeof SiteBookRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/visit': typeof SiteVisitRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/book' | '/contact' | '/services' | '/visit'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/book' | '/contact' | '/services' | '/visit' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/book'
    | '/_site/contact'
    | '/_site/services'
    | '/_site/visit'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/book': {
      id: '/_site/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof SiteBookRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/visit': {
      id: '/_site/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof SiteVisitRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBookRoute: typeof SiteBookRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteVisitRoute: typeof SiteVisitRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBookRoute: SiteBookRoute,
  SiteContactRoute: SiteContactRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteVisitRoute: SiteVisitRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
